insert into user (id, pw, nick, level, totalexp, curexp) values ('cortiz0', 'Hm9RqWSyf', 'Puce', 9, 5400, 12);
insert into user (id, pw, nick, level, totalexp, curexp) values ('cjones1', 'uylAkEg1Vfq', 'Crimson', 8, 4800, 50);
insert into user (id, pw, nick, level, totalexp, curexp) values ('kcoleman2', 'bvAt79xa', 'Purple', 20, 12000, 7);
insert into user (id, pw, nick, level, totalexp, curexp) values ('jkelly3', 'PVzrJjD5u', 'Maroon', 14, 8400, 56);
insert into user (id, pw, nick, level, totalexp, curexp) values ('jgeorge4', 'iy0d271J', 'Purple', 11, 6600, 78);
insert into user (id, pw, nick, level, totalexp, curexp) values ('clong5', 'UC1n8m', 'Blue', 4, 2400, 18);
insert into user (id, pw, nick, level, totalexp, curexp) values ('thansen6', '2cA4JVxH5', 'Maroon', 14, 8400, 10);
insert into user (id, pw, nick, level, totalexp, curexp) values ('awillis7', 'QCtxejbbp2', 'Goldenrod', 10, 6000, 11);
insert into user (id, pw, nick, level, totalexp, curexp) values ('jbowman8', 'Fx51JI', 'Crimson', 2, 1200, 20);
insert into user (id, pw, nick, level, totalexp, curexp) values ('jcarroll9', '2ii590XYOW', 'Khaki', 1, 600, 17);
insert into user (id, pw, nick, level, totalexp, curexp) values ('cmitchella', 'cu8cGDaw3P3T', 'Khaki', 5, 3000, 67);
insert into user (id, pw, nick, level, totalexp, curexp) values ('rcruzb', 'j5rWpovDW', 'Turquoise', 11, 6600, 29);
insert into user (id, pw, nick, level, totalexp, curexp) values ('jwebbc', 'Wtmo3z', 'Yellow', 9, 5400, 60);
insert into user (id, pw, nick, level, totalexp, curexp) values ('bbowmand', 'ROxpLmC082', 'Mauv', 7, 4200, 22);
insert into user (id, pw, nick, level, totalexp, curexp) values ('dweste', '1HQ8LJPrVI7', 'Purple', 16, 9600, 3);
insert into user (id, pw, nick, level, totalexp, curexp) values ('pruizf', 'p894us76H', 'Red', 1, 600, 43);
insert into user (id, pw, nick, level, totalexp, curexp) values ('jmcdonaldg', 'm7MUcjQjiId', 'Purple', 5, 3000, 62);
insert into user (id, pw, nick, level, totalexp, curexp) values ('dgonzalesh', 'wBw4QUIFNEnu', 'Turquoise', 16, 9600, 28);
insert into user (id, pw, nick, level, totalexp, curexp) values ('swallacei', '0etpSBV', 'Yellow', 6, 3600, 86);
insert into user (id, pw, nick, level, totalexp, curexp) values ('bcunninghamj', 'G4dbuDN2', 'Teal', 8, 4800, 57);
insert into user (id, pw, nick, level, totalexp, curexp) values ('tsnyderk', 'oaNVFIC9HS', 'Khaki', 6, 3600, 9);
insert into user (id, pw, nick, level, totalexp, curexp) values ('cadamsl', 'TxnvIpOHMb', 'Purple', 5, 3000, 89);
insert into user (id, pw, nick, level, totalexp, curexp) values ('jbakerm', 'q3gdjlVBQi28', 'Maroon', 19, 11400, 91);
insert into user (id, pw, nick, level, totalexp, curexp) values ('mmillern', '2VwnBj', 'Red', 13, 7800, 93);
insert into user (id, pw, nick, level, totalexp, curexp) values ('lschmidto', 'iPs1SJ9WtINB', 'Pink', 10, 6000, 14);
insert into user (id, pw, nick, level, totalexp, curexp) values ('gbaileyp', '5uGLIPZG', 'Puce', 13, 7800, 87);
insert into user (id, pw, nick, level, totalexp, curexp) values ('fwoodq', 'Nxpj5B', 'Crimson', 10, 6000, 97);
insert into user (id, pw, nick, level, totalexp, curexp) values ('aramosr', 'QNG3Z6bdg', 'Puce', 18, 10800, 52);
insert into user (id, pw, nick, level, totalexp, curexp) values ('lkims', 'Fmjrsyof', 'Indigo', 13, 7800, 81);
insert into user (id, pw, nick, level, totalexp, curexp) values ('kbennettt', '8P0AeeCfR', 'Goldenrod', 14, 8400, 80);
insert into user (id, pw, nick, level, totalexp, curexp) values ('pcarpenteru', '9Fvbd7k6L', 'Indigo', 6, 3600, 49);
insert into user (id, pw, nick, level, totalexp, curexp) values ('fmoorev', 'RJytpl', 'Goldenrod', 13, 7800, 65);
insert into user (id, pw, nick, level, totalexp, curexp) values ('lgeorgew', '4ttFzA', 'Green', 16, 9600, 41);
insert into user (id, pw, nick, level, totalexp, curexp) values ('mreyesx', '5pXNLSzFQ', 'Purple', 2, 1200, 21);
insert into user (id, pw, nick, level, totalexp, curexp) values ('nlynchy', 'zVNgWoNc0', 'Crimson', 2, 1200, 94);
insert into user (id, pw, nick, level, totalexp, curexp) values ('erussellz', 'EfE45j', 'Khaki', 12, 7200, 49);
insert into user (id, pw, nick, level, totalexp, curexp) values ('kmitchell10', 'CdOA8IvKdr', 'Mauv', 15, 9000, 53);
insert into user (id, pw, nick, level, totalexp, curexp) values ('rruiz11', 'lkjqQp', 'Mauv', 4, 2400, 93);
insert into user (id, pw, nick, level, totalexp, curexp) values ('cbutler12', 'yCleG8', 'Teal', 12, 7200, 58);
insert into user (id, pw, nick, level, totalexp, curexp) values ('dthomas13', '35jnCqN5', 'Purple', 7, 4200, 28);
insert into user (id, pw, nick, level, totalexp, curexp) values ('dharper14', '4M5mwJwjs', 'Purple', 13, 7800, 45);
insert into user (id, pw, nick, level, totalexp, curexp) values ('jmoore15', 'RmJSOuUz8t', 'Turquoise', 11, 6600, 62);
insert into user (id, pw, nick, level, totalexp, curexp) values ('phunter16', '0JlD4ss4A', 'Violet', 14, 8400, 67);
insert into user (id, pw, nick, level, totalexp, curexp) values ('jellis17', 'mpaTkcHgFO', 'Maroon', 14, 8400, 99);
insert into user (id, pw, nick, level, totalexp, curexp) values ('ccrawford18', 'Pqo3l0ABhViL', 'Teal', 4, 2400, 7);
insert into user (id, pw, nick, level, totalexp, curexp) values ('rsullivan19', 'HYueb5', 'Teal', 20, 12000, 7);
insert into user (id, pw, nick, level, totalexp, curexp) values ('chawkins1a', 'x5FflEim', 'Fuscia', 15, 9000, 15);
insert into user (id, pw, nick, level, totalexp, curexp) values ('hharris1b', 'RtDsqVo', 'Indigo', 17, 10200, 33);
insert into user (id, pw, nick, level, totalexp, curexp) values ('croberts1c', 'oWZalvWNCL4I', 'Yellow', 4, 2400, 79);
insert into user (id, pw, nick, level, totalexp, curexp) values ('drobinson1d', '99RulNLUqAj', 'Puce', 1, 600, 30);
insert into user (id, pw, nick, level, totalexp, curexp) values ('kbaker1e', 'm64gU1I', 'Green', 5, 3000, 45);
insert into user (id, pw, nick, level, totalexp, curexp) values ('kjenkins1f', 'rCbgmBl60', 'Teal', 11, 6600, 67);
insert into user (id, pw, nick, level, totalexp, curexp) values ('tgriffin1g', 'PPb42KAi', 'Blue', 9, 5400, 75);
insert into user (id, pw, nick, level, totalexp, curexp) values ('pgordon1h', 'GAA0Xl', 'Orange', 7, 4200, 100);
insert into user (id, pw, nick, level, totalexp, curexp) values ('djackson1i', 'QiSYBY', 'Violet', 3, 1800, 53);
insert into user (id, pw, nick, level, totalexp, curexp) values ('jbutler1j', '0XRNKa41zC', 'Puce', 20, 12000, 35);
insert into user (id, pw, nick, level, totalexp, curexp) values ('thanson1k', 'BZZK0xi1', 'Violet', 13, 7800, 88);
insert into user (id, pw, nick, level, totalexp, curexp) values ('fburke1l', 'wLbQ08dx', 'Pink', 16, 9600, 44);
insert into user (id, pw, nick, level, totalexp, curexp) values ('plawson1m', 'LYERq8', 'Puce', 17, 10200, 64);
insert into user (id, pw, nick, level, totalexp, curexp) values ('tstone1n', 'j1lOva', 'Violet', 14, 8400, 94);
insert into user (id, pw, nick, level, totalexp, curexp) values ('lhawkins1o', 'UgnOQDY', 'Pink', 8, 4800, 73);
insert into user (id, pw, nick, level, totalexp, curexp) values ('rwallace1p', 'u42k41ivfh', 'Mauv', 1, 600, 25);
insert into user (id, pw, nick, level, totalexp, curexp) values ('tstevens1q', 'zKUBm2LVcHbi', 'Crimson', 13, 7800, 48);
insert into user (id, pw, nick, level, totalexp, curexp) values ('eburns1r', 'QUp5aflj6Ph', 'Yellow', 11, 6600, 92);
insert into user (id, pw, nick, level, totalexp, curexp) values ('lbradley1s', '7YMbZX3m', 'Maroon', 11, 6600, 67);
insert into user (id, pw, nick, level, totalexp, curexp) values ('jvasquez1t', 'XLe9RvN', 'Orange', 20, 12000, 27);
insert into user (id, pw, nick, level, totalexp, curexp) values ('rcook1u', 'V1zR67', 'Purple', 19, 11400, 72);
insert into user (id, pw, nick, level, totalexp, curexp) values ('jbrooks1v', 'E6PsXbO44qh0', 'Aquamarine', 7, 4200, 81);
insert into user (id, pw, nick, level, totalexp, curexp) values ('asims1w', 'KYajsp', 'Teal', 1, 600, 57);
insert into user (id, pw, nick, level, totalexp, curexp) values ('areed1x', '91VQgyy1evUX', 'Aquamarine', 10, 6000, 3);
insert into user (id, pw, nick, level, totalexp, curexp) values ('acrawford1y', 'nm7AQz9jH6', 'Turquoise', 6, 3600, 37);
insert into user (id, pw, nick, level, totalexp, curexp) values ('ischmidt1z', 'SLC0o4UZDGG', 'Pink', 13, 7800, 34);
insert into user (id, pw, nick, level, totalexp, curexp) values ('dgrant20', 'BdmFLj2hDn', 'Indigo', 3, 1800, 37);
insert into user (id, pw, nick, level, totalexp, curexp) values ('wortiz21', 'GWmlbb', 'Indigo', 11, 6600, 12);
insert into user (id, pw, nick, level, totalexp, curexp) values ('tdiaz22', 'QPKo9k8pHfMm', 'Blue', 11, 6600, 50);
insert into user (id, pw, nick, level, totalexp, curexp) values ('sshaw23', '6KJpDBHBRn', 'Blue', 6, 3600, 39);
insert into user (id, pw, nick, level, totalexp, curexp) values ('cnguyen24', 'wjtIIU0KPru', 'Blue', 20, 12000, 9);
insert into user (id, pw, nick, level, totalexp, curexp) values ('chicks25', 'YBOyqvUOHgC', 'Violet', 11, 6600, 62);
insert into user (id, pw, nick, level, totalexp, curexp) values ('hbell26', 'jD9Fh6H', 'Pink', 10, 6000, 71);
insert into user (id, pw, nick, level, totalexp, curexp) values ('whamilton27', 'z9zHr3LeYEi', 'Puce', 11, 6600, 61);
insert into user (id, pw, nick, level, totalexp, curexp) values ('dwallace28', 'XRud0rNBG', 'Aquamarine', 7, 4200, 18);
insert into user (id, pw, nick, level, totalexp, curexp) values ('jwilson29', 's1LEbJ2o1', 'Red', 6, 3600, 27);
insert into user (id, pw, nick, level, totalexp, curexp) values ('hellis2a', 'WnaDqhfZ', 'Blue', 9, 5400, 86);
insert into user (id, pw, nick, level, totalexp, curexp) values ('ecastillo2b', 'sTAHVyWa', 'Goldenrod', 12, 7200, 60);
insert into user (id, pw, nick, level, totalexp, curexp) values ('nallen2c', 'V3O4Wv5', 'Mauv', 8, 4800, 85);
insert into user (id, pw, nick, level, totalexp, curexp) values ('jholmes2d', 'fmiz24qO', 'Mauv', 13, 7800, 84);
insert into user (id, pw, nick, level, totalexp, curexp) values ('sgarcia2e', 'EJqxKr7n3', 'Goldenrod', 9, 5400, 6);
insert into user (id, pw, nick, level, totalexp, curexp) values ('marnold2f', 'LjjMZWn5Gi', 'Indigo', 19, 11400, 59);
insert into user (id, pw, nick, level, totalexp, curexp) values ('abowman2g', '8nyecQ', 'Violet', 10, 6000, 26);
insert into user (id, pw, nick, level, totalexp, curexp) values ('rruiz2h', 'azknQyFSaF', 'Puce', 4, 2400, 6);
insert into user (id, pw, nick, level, totalexp, curexp) values ('ncollins2i', 'r9SCVbtV2', 'Yellow', 10, 6000, 19);
insert into user (id, pw, nick, level, totalexp, curexp) values ('cfrazier2j', 'BwrNWgoG6R4', 'Red', 12, 7200, 60);
insert into user (id, pw, nick, level, totalexp, curexp) values ('rfoster2k', '19mHvF', 'Goldenrod', 16, 9600, 20);
insert into user (id, pw, nick, level, totalexp, curexp) values ('rdavis2l', 'fwRpuG35', 'Turquoise', 7, 4200, 61);
insert into user (id, pw, nick, level, totalexp, curexp) values ('chayes2m', 'CytHyTGAx', 'Indigo', 1, 600, 69);
insert into user (id, pw, nick, level, totalexp, curexp) values ('rray2n', 'osh9rk49bs5', 'Puce', 18, 10800, 89);
insert into user (id, pw, nick, level, totalexp, curexp) values ('rgonzalez2o', 'NCyIJTpVJ', 'Violet', 11, 6600, 74);
insert into user (id, pw, nick, level, totalexp, curexp) values ('jalexander2p', 'hH5jFNw', 'Crimson', 20, 12000, 5);
insert into user (id, pw, nick, level, totalexp, curexp) values ('igonzales2q', 'v4sGlPz0', 'Khaki', 6, 3600, 32);
insert into user (id, pw, nick, level, totalexp, curexp) values ('swillis2r', 'BtF6UbT85e8', 'Puce', 14, 8400, 73);


INSERT INTO quiz (category, name) VALUES ('과일', '감');
INSERT INTO quiz (category, name) VALUES ('과일', '복숭아');
INSERT INTO quiz (category, name) VALUES ('과일', '바나나');
INSERT INTO quiz (category, name) VALUES ('과일', '배');
INSERT INTO quiz (category, name) VALUES ('과일', '사과');
INSERT INTO quiz (category, name) VALUES ('과일', '수박');
INSERT INTO quiz (category, name) VALUES ('과일', '오렌지');
INSERT INTO quiz (category, name) VALUES ('과일', '참외');
INSERT INTO quiz (category, name) VALUES ('과일', '포도');
INSERT INTO quiz (category, name) VALUES ('과일', '레몬');
INSERT INTO quiz (category, name) VALUES ('과일', '밤');
INSERT INTO quiz (category, name) VALUES ('과일', '호두');

// 300(1.5^level-1)/1.5-1